# Generated by Django 4.2.4 on 2023-08-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biografia',
            field=models.CharField(default='Usuario de Lev', max_length=60),
        ),
    ]
