# Generated by Django 4.2.4 on 2023-08-12 03:08

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_image_imagefiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='image',
        ),
        migrations.DeleteModel(
            name='ImageFiles',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(blank=True, upload_to=home.models.user_directory_path),
        ),
    ]
