# Generated by Django 4.2.4 on 2023-08-12 18:18

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_imagepost_image_delete_imagefiles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=home.models.user_directory_path),
        ),
        migrations.DeleteModel(
            name='ImagePost',
        ),
    ]
